Repository usha-madithati/esmart.github.io, pull requests merged in 2024-07, with the labels that each got.

#362 added links for email,facebook,insta
  package-lock.json
  package.json
  src/components/Footer.js
Labels: gssoc, level1

#382 Announcement Feat Added
  backend/index.js
  backend/package-lock.json
  backend/package.json
  src/App.js
  src/Dashboards/AdminD.js
  src/components/Announcement.js
  src/components/Navbar.js
Labels: gssoc, level3

#385 Needs to enable browse file button in the Scan QR page. #374
  backend/package.json
  src/pages/QR.js
Labels: gssoc, level1

#393 Server updated and contact fuctionality added
  backend/index.js
  backend/package-lock.json
  src/pages/Contact.js
Labels: gssoc, level2

#397 Feat:Want to write backend of review Page #388
  backend/Schemas/Review.schema.js
  backend/index.js
  src/pages/Review.js
Labels: gssoc

#409 Feat:Want to Add FAQ Section to The Website #405
  src/App.js
  src/components/Faq/FAQs.css
  src/components/Faq/Faq.js
  src/pages/Home.js
Labels: gssoc, level2

#460 New UI integrated and bugs fixed of no response from server
  backend/.env.sample
  src/Dashboards/DashboardOverview.css
  src/Dashboards/DashboardOverview.js
  src/Dashboards/UserD.js
  src/components/PForm.js
Labels: gssoc, level2

#458 added Live chat
  src/App.js
  src/components/ChatBox.js
  src/components/Footer.js
  src/pages/Live-chat.js
Labels: gssoc, level2
