Repository usha-madithati/esmart.github.io, pull requests merged in 2024-05, with the labels that each got.

#49 Update README.md
  README.md
Labels: GSSoC'24, #level 1

#124 MADE WHOLE RESPONSIVE UI
  .gitignore
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/Login.js
  src/pages/Signup.js
  src/reportWebVitals.js
  src/setupTests.js
Labels: GSSoC'24, #level3

#126 Docs updated and minor issues fixed
  README.md
  public/index.html
Labels: documentation, GSSoC'24, #level 1

#138 Added Logo solved #117
  package-lock.json
  src/components/Navbar.js
  src/pages/Login.js
Labels: GSSoC'24, level 1

#135 Footer Added
  src/App.js
  src/components/Footer.js
  src/pages/Contact.js
  src/pages/Home.js
  src/pages/Login.js
  src/pages/Notification.js
  src/pages/QR.js
  src/pages/Review.js
  src/pages/Signup.js
Labels: GSSoC'24, level2

#147 new notification service added
  package-lock.json
  package.json
  src/App.js
  src/components/Footer.js
  src/components/Navbar.js
  src/pages/Home.js
  src/pages/Notification.js
Labels: GSSoC'24, level2

#167 backend services added
  backend/.env.sample
  backend/.gitignore
  backend/Schemas/Products.schema.js
  backend/db/datbase.js
  backend/index.js
  backend/package-lock.json
  backend/package.json
  package-lock.json
  src/index.js
Labels: enhancement, GSSoC'24, level3

#168 validation done in login as well as signup forms
  src/pages/Login.js
  src/pages/Signup.js
Labels: enhancement, GSSoC'24, level 1

#170 DOCS UPDATION
  README.md
Labels: gssoc24, level1

#174 API LINE INTEGRATION ADDED
  backend/.env.sample
  backend/Schemas/Products.schema.js
  backend/index.js
  package-lock.json
  package.json
  src/App.js
  src/components/PForm.js
  src/index.js
  src/pages/AddProductForm.js
  src/pages/QR.js
Labels: gssoc24, level3

#178 Authetication added
  backend/Schemas/User.Schema.js
  backend/controllers/ProductController.js
  backend/controllers/UserController.js
  backend/index.js
  backend/package-lock.json
  backend/package.json
  package-lock.json
  package.json
  src/pages/Login.js
  src/pages/Signup.js
Labels: gssoc24, level3
